name: duration_picker2
description: A time picker widget that can select both minutes and hours. Fork from duration_picker.
version: 2.0.0
homepage: https://github.com/tbm98/duration_picker2

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1